### ISSUE TITLE
Cronjobs do not work

### ISSUE THREAD

**Issue by TheUltimateC0der** [digitalcanvasdesign/docker-invoiceninja-nginx#1]
`invoices.log`
```
Sat, 15 Jun 2019 08:00:01 +0000 Running SendRecurringInvoices...

In Connection.php line 647:
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `accou
  nts` where `reset_counter_frequency_id` > 0 and `accounts`.`deleted_at` is
  null order by `id` asc)

In PDOConnection.php line 47:
  SQLSTATE[HY000] [2002] No such file or directory

In PDOConnection.php line 43:
  SQLSTATE[HY000] [2002] No such file or directory
```

`reminders.log`
```
Sat, 15 Jun 2019 08:00:01 +0000 Running SendReminders...

In Connection.php line 647:
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `invoi
  ces` where is_deleted IS FALSE AND deleted_at IS NULL AND is_recurring IS F
  ALSE AND is_public IS TRUE
              AND balance > 0 AND due_date = 2019-06-15 AND recurring_invoice
  _id IS NOT NULL and `invoices`.`deleted_at` is null order by `invoices`.`id
  ` asc)

In PDOConnection.php line 47:
  SQLSTATE[HY000] [2002] No such file or directory

In PDOConnection.php line 43:
  SQLSTATE[HY000] [2002] No such file or directory
```

When I ssh into the container and do `./artisan ninja:send-invoices` or `./artisan ninja:send-reminders` everything works fine.

**Comment by jasonraimondi** [comment]
Shoot I didnt mean for this to close automatically like that. The issue should be resolved though. I have set up a dummy invoice and successfully had it send.

The cron issue should be resolved, it was actually not an issue with the cronjobs themselves, they were running correctly. The issue was rather the lack of [system environment in cron](https://www.google.com/search?client=firefox-b-1-d&ei=14sGXbfWN8TT-gTu4pKwCQ&q=environment+in+cronjobs&oq=environment+in+cronjobs&gs_l=psy-ab.3..0i13i30j0i22i10i30j0i13i5i30.1296.1999..2139...0.0..0.127.474.0j4......0....1..gws-wiz.......0i71j35i39j0i22i30.JDBNC9_jDv4) (database connection) in the invoices and reminders send cron. 

The solution was not the most beautiful, but basically at runtime I set up all the environments we need in `/.env.sh` and then source them in the `invoices` and `reminders` script located [here](https://github.com/digitalcanvasdesign/docker-invoiceninja-nginx/tree/master/bin).

Thanks for opening the ticket! Hope this resolves the issue.

**Comment by jasonraimondi** [comment]
This was where the bulk of the fix was: https://github.com/digitalcanvasdesign/docker-invoiceninja-nginx/commit/5f9d6186e63afb4d3fcd5fba5466a37ade18ea4d

**Comment by TheUltimateC0der** [comment]
Can confirm it works now. Appreciate your work :)

**Comment by jasonraimondi** [comment]
Awesome! Glad I could help.
